foreground              #FFFFFF
background              #4F2A7C
selection_foreground    #4F2A7C
selection_background    #FFFFFF
cursor                  #E9ACF2
cursor_text_color       #070807

active_tab_foreground     #4F2A7C
active_tab_background     #9D64D5
inactive_tab_foreground   #9D64D5
inactive_tab_background   #4F2A7C

# black
color0      #3B2952
color8      #70578F

# red
color1      #F8CCFF
color9      #E7AAF0

# green
color2      #D6CCFF
color10     #B8AAF0

# yellow
color3      #E6CCFF
color11     #CDAAF0

# blue
color4      #BC9AE6
color12     #BC9AE6

# magenta
color5      #A89AE6
color13     #A89AE6

# cyan
color6      #C09AE6
color14     #C09AE6

# white
color7      #F8CCFF
color15     #E7AAF0
